twilio.account_sid=AC8b675c9e216ab5a791b6151a77748ced
twilio.auth_token=44ee7a5e3e2e74678aec01d6f4c6791b
twilio.from_number=+14788878805
gmail.sender_email=g7.gonature@gmail.com
gmail.app_password=xersjiiywyxixpcz 